# Generated by Django 6.0.2 on 2026-05-26 01:28

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhorario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('horas_max_semanales', models.PositiveIntegerField(help_text='Maximo de horas semanales asignables.')),
                ('estado', models.BooleanField(db_index=True, default=True, help_text='False = inactivo/retirado.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='docentes/', validators=[users.validators.validate_imagen])),
                ('user', models.OneToOneField(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['user__apellido', 'user__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('motivo', models.TextField(blank=True, help_text='Obligatorio cuando disponible=False.')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='bhorario.bloquehorario')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='docentes.docente')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
        migrations.AddIndex(
            model_name='docente',
            index=models.Index(fields=['estado'], name='docentes_do_estado_d67109_idx'),
        ),
        migrations.AddIndex(
            model_name='docente',
            index=models.Index(fields=['especialidad'], name='docentes_do_especia_091d6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('docente', 'bloque')},
        ),
    ]
