# Generated by Django 6.0.2 on 2026-06-09 07:14

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0002_competencia_es_induccion_and_more'),
        ('docentes', '0001_initial'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilitacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('MODULO', 'Módulo completo'), ('ASIGNATURA', 'Asignatura específica')], db_index=True, max_length=12)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_desde', models.DateField(help_text='Fecha desde la que aplica esta habilitación.')),
                ('fecha_hasta', models.DateField(blank=True, help_text='Dejar en blanco si es indefinida.', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habilitación docente',
                'verbose_name_plural': 'Habilitaciones docentes',
                'ordering': ['docente', 'nivel', 'modulo', 'asignatura'],
            },
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='dia_semana',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], db_index=True, default='LUNES', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_fin_restriccion',
            field=models.DateField(blank=True, help_text='Solo si tipo_restriccion=TEMPORAL.', null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_inicio_restriccion',
            field=models.DateField(blank=True, help_text='Solo si tipo_restriccion=TEMPORAL.', null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(18, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(7, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='tipo_restriccion',
            field=models.CharField(choices=[('PERMANENTE', 'Permanente (toda la vigencia)'), ('TEMPORAL', 'Temporal (rango de fechas)')], db_index=True, default='PERMANENTE', max_length=12),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={'ordering': ['docente', 'dia_semana', 'hora_inicio'], 'verbose_name': 'Disponibilidad', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('docente', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),

        migrations.AddField(
            model_name='docente',
            name='horas_extra_autorizadas',
            field=models.PositiveSmallIntegerField(default=0, help_text='Horas adicionales autorizadas sobre el máximo regular. Solo aplica si permite_horas_extra=True.'),
        ),
        migrations.AddField(
            model_name='docente',
            name='permite_horas_extra',
            field=models.BooleanField(default=False, help_text='Autoriza asignación por encima del máximo semanal regular.'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='disponible',
            field=models.BooleanField(default=True, help_text='False = el docente no puede en este slot.'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado',
            field=models.BooleanField(default=True, help_text='False = inactivo/retirado.'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='horas_max_semanales',
            field=models.PositiveIntegerField(default=40, help_text='Máximo de horas semanales regulares. Por norma SENA: 40h.'),
        ),
        migrations.AddIndex(
            model_name='disponibilidad',
            index=models.Index(fields=['docente', 'dia_semana'], name='docentes_di_docente_d470df_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidad',
            index=models.Index(fields=['disponible'], name='docentes_di_disponi_815098_idx'),
        ),
        migrations.AddField(
            model_name='habilitaciondocente',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones_docentes', to='competencia.asignatura'),
        ),
        migrations.AddField(
            model_name='habilitaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitaciones', to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='habilitaciondocente',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones_docentes', to='programa.modulo'),
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='bloque',
        ),
        migrations.AddIndex(
            model_name='habilitaciondocente',
            index=models.Index(fields=['docente', 'nivel', 'activo'], name='docentes_ha_docente_7f2843_idx'),
        ),
        migrations.AddIndex(
            model_name='habilitaciondocente',
            index=models.Index(fields=['modulo', 'activo'], name='docentes_ha_modulo__b3a69d_idx'),
        ),
        migrations.AddIndex(
            model_name='habilitaciondocente',
            index=models.Index(fields=['asignatura', 'activo'], name='docentes_ha_asignat_2bb89e_idx'),
        ),
        migrations.AddConstraint(
            model_name='habilitaciondocente',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('nivel', 'MODULO')), fields=('docente', 'modulo'), name='unique_habilitacion_modulo_activa'),
        ),
        migrations.AddConstraint(
            model_name='habilitaciondocente',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('nivel', 'ASIGNATURA')), fields=('docente', 'asignatura'), name='unique_habilitacion_asignatura_activa'),
        ),
    ]
