# Generated by Django 6.0.2 on 2026-05-26 01:27

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import users.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo'), ('COORDINADOR', 'Coordinación'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios/', validators=[users.validators.validate_imagen])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellido', 'nombre'],
                'permissions': [('ver_estudiantes', 'Puede ver estudiantes'), ('ver_docentes', 'Puede ver docentes'), ('ver_administrativos', 'Puede ver administrativos'), ('ver_coordinadores', 'Puede ver coordinadores'), ('ver_horarios', 'Puede ver horarios'), ('crear_usuarios', 'Puede crear usuarios'), ('editar_usuarios', 'Puede editar usuarios'), ('desactivar_usuarios', 'Puede desactivar usuarios'), ('eliminar_usuarios', 'Puede eliminar usuarios'), ('gestionar_permisos', 'Puede gestionar permisos'), ('gestionar_roles', 'Puede gestionar roles')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de cambio de correo',
                'verbose_name_plural': 'Solicitudes de cambio de correo',
                'indexes': [models.Index(fields=['user', 'is_used'], name='users_email_user_id_cb8c0c_idx'), models.Index(fields=['new_email'], name='users_email_new_ema_f1cc7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de correo',
                'verbose_name_plural': 'Verificaciones de correo',
                'indexes': [models.Index(fields=['user', 'code'], name='users_email_user_id_ac5510_idx'), models.Index(fields=['is_verified'], name='users_email_is_veri_504018_idx'), models.Index(fields=['is_used'], name='users_email_is_used_2c0db0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restablecimiento de contraseña',
                'verbose_name_plural': 'Restablecimientos de contraseña',
                'indexes': [models.Index(fields=['token'], name='users_passw_token_2def9c_idx'), models.Index(fields=['user', 'is_used'], name='users_passw_user_id_61b761_idx')],
            },
        ),
    ]
