# Generated by Django 6.0.2 on 2026-06-24 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Restablecimiento de contraseña', 'verbose_name_plural': 'Restablecimientos de contraseña'},
        ),
        migrations.RemoveIndex(
            model_name='passwordreset',
            name='users_passw_token_2def9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordreset',
            name='users_passw_user_id_61b761_idx',
        ),
        migrations.RenameField(
            model_name='passwordreset',
            old_name='is_used',
            new_name='used',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='code',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='expires_at',
        ),
    ]
