# Generated by Django 6.0.2 on 2026-05-26 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push (app)')], default='PUSH', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida')], db_index=True, default='PENDIENTE', max_length=15)),
                ('intentos', models.PositiveSmallIntegerField(default=0, help_text='Numero de intentos de entrega realizados.')),
                ('error_detalle', models.TextField(blank=True, help_text='Detalle del ultimo error si estado=FALLIDA.')),
                ('tarea_id', models.CharField(blank=True, help_text='ID de tarea Celery para rastreo/cancelacion.', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Momento en que se confirmo el envio exitoso.', null=True)),
                ('alerta', models.ForeignKey(help_text='Alerta que origina esta notificacion.', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='alertas.alerta')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'canal'], name='notificacio_estado_714029_idx'), models.Index(fields=['destinatario', 'estado'], name='notificacio_destina_458974_idx')],
                'unique_together': {('alerta', 'destinatario', 'canal')},
            },
        ),
    ]
