# Generated by Django 6.0.2 on 2026-05-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='alertas.alerta'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='error_detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tarea_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
