# Generated by Django 6.0.2 on 2026-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_alerta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('APP', 'Notificación App')], default='APP', max_length=10),
        ),
    ]
