# Generated by Django 6.0.2 on 2026-05-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('TEORICA', 'Teórica'), ('PRACTICA', 'Práctica'), ('TEORICO_PRACTICA', 'Teórico-Práctica')], db_index=True, default='TEORICO_PRACTICA', max_length=20)),
                ('horas_lectivas', models.PositiveIntegerField()),
                ('horas_practicas', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField(help_text='Posición de la asignatura dentro del módulo.')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], db_index=True, default='ACTIVA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='programa.modulo')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['modulo', 'orden'],
                'unique_together': {('modulo', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('TRANSVERSAL', 'Transversal')], db_index=True, default='PRINCIPAL', max_length=15)),
                ('codigo', models.CharField(help_text='Código único. Ej: COMP-001.', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('horas_trimestre_transversal', models.PositiveIntegerField(blank=True, help_text='Solo aplica para competencias transversales.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(blank=True, help_text='Null si es transversal (pertenece al centro, no a un módulo).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='competencia.asignatura')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único. Ej: RAP-001.', max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('criterios_evaluacion', models.TextField(blank=True, help_text='Criterios con los que se evalúa el resultado.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='competencia.competencia')),
            ],
            options={
                'verbose_name': 'Resultado de aprendizaje',
                'verbose_name_plural': 'Resultados de aprendizaje',
                'ordering': ['competencia', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docentes_asignados', to='competencia.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas_asignadas', to='docentes.docente')),
            ],
            options={
                'verbose_name': 'Docente por asignatura',
                'verbose_name_plural': 'Docentes por asignatura',
                'ordering': ['asignatura', 'docente'],
                'unique_together': {('docente', 'asignatura')},
            },
        ),
    ]
