# Generated by Django 6.0.2 on 2026-06-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='es_induccion',
            field=models.BooleanField(default=False, help_text='Marca esta competencia transversal como inducción obligatoria en trimestre 1.'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='induccion_activa',
            field=models.BooleanField(default=True, help_text='Permite al administrador desactivar la inducción.'),
        ),
    ]
