# Generated by Django 6.0.2 on 2026-06-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0002_competencia_es_induccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocenteAsignatura',
        ),
    ]
