# Generated by Django 6.0.2 on 2026-06-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa', '0003_delete_docentemodulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliticaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True)),
                ('fichas_activas', models.PositiveIntegerField(default=0)),
                ('fichas_lectiva', models.PositiveIntegerField(default=0)),
                ('fichas_productiva', models.PositiveIntegerField(default=0)),
                ('estudiantes_activos', models.PositiveIntegerField(default=0)),
                ('deserciones_mes', models.PositiveIntegerField(default=0)),
                ('graduados_mes', models.PositiveIntegerField(default=0)),
                ('reasignaciones_mes', models.PositiveIntegerField(default=0)),
                ('docentes_activos', models.PositiveIntegerField(default=0)),
                ('docentes_sobrecargados', models.PositiveIntegerField(default=0, help_text='Docentes que superan su horas_max_efectivas en la semana.')),
                ('aulas_activas', models.PositiveIntegerField(default=0)),
                ('aulas_mantenimiento', models.PositiveIntegerField(default=0)),
                ('aulas_inactivas', models.PositiveIntegerField(default=0)),
                ('planes_aprobados', models.PositiveIntegerField(default=0)),
                ('planes_pendientes', models.PositiveIntegerField(default=0)),
                ('alertas_pendientes', models.PositiveIntegerField(default=0)),
                ('conflictos_horario_mes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot de analítica',
                'verbose_name_plural': 'Snapshots de analítica',
                'ordering': ['-fecha'],
                'get_latest_by': 'fecha',
            },
        ),
        migrations.CreateModel(
            name='SnapshotPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichas_activas', models.PositiveIntegerField(default=0)),
                ('fichas_lectiva', models.PositiveIntegerField(default=0)),
                ('fichas_productiva', models.PositiveIntegerField(default=0)),
                ('estudiantes_activos', models.PositiveIntegerField(default=0)),
                ('deserciones_mes', models.PositiveIntegerField(default=0)),
                ('graduados_mes', models.PositiveIntegerField(default=0)),
                ('avance_curricular_pct', models.DecimalField(decimal_places=2, default=0, help_text='Promedio de porcentaje de avance de las fichas activas.', max_digits=5)),
                ('horas_planificadas', models.PositiveIntegerField(default=0)),
                ('horas_ejecutadas', models.PositiveIntegerField(default=0)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='programa.programa')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='analitica.analiticasnapshot')),
            ],
            options={
                'verbose_name': 'Snapshot por programa',
                'verbose_name_plural': 'Snapshots por programa',
                'ordering': ['snapshot', 'programa'],
                'indexes': [models.Index(fields=['programa', 'snapshot'], name='analitica_s_program_4d8b6b_idx')],
                'unique_together': {('snapshot', 'programa')},
            },
        ),
    ]
