# Generated by Django 6.0.2 on 2026-05-26 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhorario', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONFLICTO', 'Conflicto de horario'), ('DISPONIBILIDAD', 'Disponibilidad'), ('SISTEMA', 'Sistema')], db_index=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('formato_alerta', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('APP', 'Notificación App')], default='APP', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('LEIDA', 'Leída')], db_index=True, default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Momento en que el usuario leyó la alerta.', null=True)),
                ('bloque_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='bhorario.bloquehorario')),
                ('destinatario', models.ForeignKey(blank=True, help_text='Usuario al que va dirigida la alerta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'tipo'], name='alertas_ale_estado_9b7085_idx'), models.Index(fields=['destinatario', 'estado'], name='alertas_ale_destina_540db3_idx')],
            },
        ),
    ]
