# Generated by Django 6.0.2 on 2026-06-18 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FICHAS', 'Fichas'), ('ESTUDIANTES', 'Estudiantes'), ('DOCENTES', 'Docentes'), ('HORARIOS', 'Horarios'), ('COMPETENCIAS', 'Competencias'), ('AULAS', 'Aulas'), ('PLANES', 'Planes trimestrales'), ('ANALITICA', 'Analítica'), ('COMPLETA', 'Base de datos completa')], db_index=True, max_length=15)),
                ('formato', models.CharField(choices=[('EXCEL', 'Excel (.xlsx)'), ('CSV', 'CSV'), ('PDF', 'PDF'), ('JSON', 'JSON')], db_index=True, max_length=10)),
                ('filtros', models.JSONField(default=dict, help_text='Parámetros aplicados al exportar (fechas, programa, ficha, etc.).')),
                ('registros_exportados', models.PositiveIntegerField(default=0, help_text='Cantidad de registros incluidos en la exportación.')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la exportación.', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la exportación.', on_delete=django.db.models.deletion.PROTECT, related_name='exportaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de exportación',
                'verbose_name_plural': 'Registros de exportación',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='exportacion_usuario_ae6698_idx'), models.Index(fields=['tipo', 'fecha'], name='exportacion_tipo_a921c5_idx')],
            },
        ),
    ]
