# Generated by Django 6.0.2 on 2026-05-26 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhorario', '0003_initial'),
        ('competencia', '0001_initial'),
        ('docentes', '0001_initial'),
        ('ficha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_asignadas', models.PositiveIntegerField(help_text='Horas totales planificadas para esta competencia.')),
                ('orden', models.PositiveIntegerField(help_text='Orden de dictado dentro del trimestre.')),
                ('completado', models.BooleanField(default=False)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_plan', to='competencia.competencia')),
                ('docente', models.ForeignKey(blank=True, help_text='Docente asignado a esta competencia en este trimestre.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_plan', to='docentes.docente')),
            ],
            options={
                'verbose_name': 'Item de plan',
                'verbose_name_plural': 'Items de plan',
                'ordering': ['plan', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='BloqueCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_ejecutadas', models.DecimalField(decimal_places=1, help_text='Horas reales ejecutadas en este bloque.', max_digits=4)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bloque', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='competencia_asignada', to='bhorario.bloquehorario')),
                ('item_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques_ejecutados', to='planificacion.itemplan')),
            ],
            options={
                'verbose_name': 'Bloque de competencia',
                'verbose_name_plural': 'Bloques de competencia',
            },
        ),
        migrations.CreateModel(
            name='PlanTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveIntegerField(help_text='Numero de trimestre al que aplica este plan.')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('aprobado', models.BooleanField(db_index=True, default=False, help_text='Solo planes aprobados permiten generar horarios.')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_trimestrales', to='ficha.ficha')),
            ],
            options={
                'verbose_name': 'Plan trimestral',
                'verbose_name_plural': 'Planes trimestrales',
                'ordering': ['ficha', 'trimestre'],
                'unique_together': {('ficha', 'trimestre')},
            },
        ),
        migrations.AddField(
            model_name='itemplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='planificacion.plantrimestral'),
        ),
        migrations.AlterUniqueTogether(
            name='itemplan',
            unique_together={('plan', 'competencia')},
        ),
    ]
