# Generated by Django 6.0.2 on 2026-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemplan',
            options={'ordering': ['plan', 'orden'], 'verbose_name': 'Ítem de plan', 'verbose_name_plural': 'Ítems de plan'},
        ),
        migrations.RemoveField(
            model_name='plantrimestral',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='plantrimestral',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('EN_EJECUCION', 'En ejecución'), ('CERRADO', 'Cerrado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=15),
        ),
        migrations.AddField(
            model_name='plantrimestral',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Obligatorio si estado=RECHAZADO.'),
        ),
        migrations.AlterField(
            model_name='plantrimestral',
            name='trimestre',
            field=models.PositiveIntegerField(help_text='Número de trimestre al que aplica este plan.'),
        ),
    ]
