# Generated by Django 6.0.2 on 2026-05-26 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fichas', 'Fichas'), ('docentes', 'Docentes'), ('horarios', 'Horarios'), ('competencias', 'Competencias'), ('aulas', 'Aulas'), ('analitica', 'Analitica')], db_index=True, max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], db_index=True, default='pendiente', max_length=15)),
                ('filtros', models.JSONField(default=dict, help_text='Filtros aplicados al generar el reporte.')),
                ('tarea_id', models.CharField(blank=True, help_text='ID de tarea Celery.', max_length=255, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/pdf/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/excel/')),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si estado=error.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte generado',
                'verbose_name_plural': 'Reportes generados',
                'ordering': ['-created_at'],
            },
        ),
    ]
