# Generated by Django 6.0.2 on 2026-06-18 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegenerado',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('LISTO', 'Listo'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo',
            field=models.CharField(choices=[('FICHAS', 'Fichas'), ('DOCENTES', 'Docentes'), ('HORARIOS', 'Horarios'), ('COMPETENCIAS', 'Competencias'), ('AULAS', 'Aulas'), ('ANALITICA', 'Analítica'), ('NOVEDADES', 'Novedades')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FICHA_SIN_PLAN', 'Ficha sin plan aprobado'), ('DOCENTE_SOBRECARGADO', 'Docente sobrecargado'), ('AULA_CONFLICTO', 'Aula con conflicto'), ('AVANCE_BAJO', 'Avance curricular bajo'), ('ESTUDIANTE_EN_RIESGO', 'Estudiante en riesgo'), ('PLAN_SIN_DOCENTE', 'Competencia sin docente asignado'), ('FICHA_SIN_HORARIO', 'Ficha sin horario generado'), ('OTRA', 'Otra')], db_index=True, max_length=30)),
                ('prioridad', models.PositiveSmallIntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], db_index=True, default=2)),
                ('titulo', models.CharField(help_text='Resumen corto visible en el listado.', max_length=200)),
                ('descripcion', models.TextField(help_text='Detalle completo de la novedad.')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID de la entidad afectada.', null=True)),
                ('generada_por_sistema', models.BooleanField(default=True, help_text='True = generada automáticamente por Celery. False = manual.')),
                ('atendida', models.BooleanField(db_index=True, default=False)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('nota_atencion', models.TextField(blank=True, help_text='Qué se hizo para resolver la novedad.')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Si se define, la novedad se ignora automáticamente después de esta fecha.', null=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_atendidas', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de entidad afectada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('generada_por', models.ForeignKey(blank=True, help_text='Solo si generada_por_sistema=False.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['prioridad', '-fecha_generacion'],
                'indexes': [models.Index(fields=['tipo', 'atendida'], name='reportes_no_tipo_4ff5c2_idx'), models.Index(fields=['prioridad', 'atendida'], name='reportes_no_priorid_6ab825_idx'), models.Index(fields=['content_type', 'object_id'], name='reportes_no_content_84802f_idx')],
            },
        ),
    ]
