# Generated by Django 6.0.2 on 2026-06-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reportegenerado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo',
            field=models.CharField(choices=[('FICHAS', 'Fichas'), ('DOCENTES', 'Docentes'), ('HORARIOS', 'Horarios'), ('COMPETENCIAS', 'Competencias'), ('AULAS', 'Aulas'), ('ANALITICA', 'Analítica'), ('NOVEDADES', 'Novedades'), ('PLANES', 'Planes')], db_index=True, max_length=20),
        ),
    ]
