# Generated by Django 6.0.2 on 2026-05-26 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ficha', models.CharField(db_index=True, max_length=20, unique=True)),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('MIXTA', 'Mixta')], db_index=True, max_length=10)),
                ('numero_estudiantes_estimado', models.PositiveIntegerField(help_text='Cupo estimado al crear la ficha.')),
                ('etapa', models.CharField(choices=[('LECTIVA', 'Lectiva'), ('PRODUCTIVA', 'Productiva')], db_index=True, default='LECTIVA', max_length=15)),
                ('horas_semanales_objetivo', models.PositiveIntegerField()),
                ('trimestre', models.PositiveIntegerField(help_text='Trimestre de formación en curso.')),
                ('estado', models.BooleanField(db_index=True, default=True)),
                ('cadena_formacion', models.BooleanField(default=False, help_text='Indica si la ficha está en cadena de formación.')),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jefe_grupo', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_jefe', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='programa.versionprograma')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['-fecha_inicio', 'codigo_ficha'],
            },
        ),
        migrations.CreateModel(
            name='FichaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('es_cadena', models.BooleanField(default=False, help_text='True si el estudiante ingresó por cadena de formación (reduce tiempo en etapa lectiva).')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, choices=[('DESERCION', 'Deserción'), ('RETIRO_VOLUNTARIO', 'Retiro voluntario'), ('CANCELADO', 'Cancelado por rendimiento'), ('GRADUADO', 'Graduado'), ('REASIGNADO', 'Reasignado a otra ficha')], db_index=True, help_text='Obligatorio al desactivar al estudiante.', max_length=20, null=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='ficha.ficha')),
            ],
            options={
                'verbose_name': 'Estudiante en ficha',
                'verbose_name_plural': 'Estudiantes en ficha',
                'ordering': ['ficha', 'estudiante__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(choices=[('LECTIVA', 'Lectiva'), ('PRODUCTIVA', 'Productiva')], max_length=15)),
                ('etapa_nueva', models.CharField(choices=[('LECTIVA', 'Lectiva'), ('PRODUCTIVA', 'Productiva')], max_length=15)),
                ('trimestre', models.PositiveIntegerField(help_text='Trimestre en el momento del cambio.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_etapa', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_etapas', to='ficha.ficha')),
            ],
            options={
                'verbose_name': 'Historial de etapa',
                'verbose_name_plural': 'Historial de etapas',
                'ordering': ['ficha', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReasignacionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Motivo de la reasignación (cambio de jornada, cupo, etc.).')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones', to=settings.AUTH_USER_MODEL)),
                ('ficha_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_entrada', to='ficha.ficha')),
                ('ficha_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_salida', to='ficha.ficha')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reasignación de ficha',
                'verbose_name_plural': 'Reasignaciones de ficha',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='ficha',
            index=models.Index(fields=['estado', 'etapa'], name='ficha_ficha_estado_1803f9_idx'),
        ),
        migrations.AddIndex(
            model_name='ficha',
            index=models.Index(fields=['jornada'], name='ficha_ficha_jornada_42d2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='fichaestudiante',
            index=models.Index(fields=['activo'], name='ficha_ficha_activo_062ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='fichaestudiante',
            index=models.Index(fields=['es_cadena'], name='ficha_ficha_es_cade_35dd63_idx'),
        ),
        migrations.AddIndex(
            model_name='fichaestudiante',
            index=models.Index(fields=['motivo_retiro'], name='ficha_ficha_motivo__64c373_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fichaestudiante',
            unique_together={('ficha', 'estudiante')},
        ),
    ]
