# Generated by Django 6.0.2 on 2026-06-18 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_migrate_legacy_habilitaciones'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('CERRADA', 'Cerrada')], db_index=True, default='ACTIVA', max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='jefe_grupo',
            field=models.ForeignKey(blank=True, help_text='Docente responsable del grupo. Debe tener perfil activo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_jefe', to='docentes.docente'),
        ),
    ]
