# Generated by Django 6.0.2 on 2026-05-26 01:27

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades de este equipamiento.')),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie. Opcional para ítems genéricos.', max_length=100, null=True, unique=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('FUNC', 'Funcional'), ('DAN', 'Dañado'), ('MANT', 'En mantenimiento')], db_index=True, default='FUNC', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipamiento/', validators=[users.validators.validate_imagen_5mb])),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('pisos', models.PositiveIntegerField(help_text='Número de pisos del bloque.')),
                ('capacidad_maxima', models.PositiveIntegerField(help_text='Capacidad total de personas en el bloque.')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('MANT', 'Mantenimiento'), ('INAC', 'Inactivo')], db_index=True, default='ACT', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bloques/', validators=[users.validators.validate_imagen_5mb])),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado'], name='aulas_bloqu_estado_c64527_idx')],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aula', models.CharField(db_index=True, max_length=10, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo_aula', models.CharField(choices=[('LAB', 'Laboratorio'), ('TEO', 'Teórica'), ('SIS', 'Sistemas de Información'), ('OTR', 'Otro')], max_length=10)),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('MANT', 'Mantenimiento'), ('INAC', 'Inactiva')], default='ACT', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='aulas/', validators=[users.validators.validate_imagen_5mb])),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='aulas.bloque')),
                ('equipamiento', models.ManyToManyField(blank=True, related_name='aulas', to='aulas.equipamiento')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['bloque', 'codigo_aula'],
                'indexes': [models.Index(fields=['estado'], name='aulas_aula_estado_10fe90_idx'), models.Index(fields=['tipo_aula'], name='aulas_aula_tipo_au_722c35_idx'), models.Index(fields=['bloque', 'estado'], name='aulas_aula_bloque__16fed9_idx')],
            },
        ),
    ]
