# Generated by Django 6.0.2 on 2026-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='piso',
            field=models.PositiveIntegerField(default=1, help_text='Piso del bloque donde se ubica el aula.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
