# Generated by Django 6.0.2 on 2026-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_aula_piso_alter_equipamiento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('MANT', 'Mantenimiento'), ('INAC', 'Inactivo')], default='ACT', max_length=10),
        ),
    ]
