# Generated by Django 6.0.2 on 2026-05-26 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('TECNICO', 'Tecnico'), ('TECNOLOGIA', 'Tecnologia'), ('CURSO_CORTO', 'Curso Corto')], db_index=True, default='TECNICO', max_length=20)),
                ('horas_lectivas', models.PositiveIntegerField()),
                ('horas_practicas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_REVISION', 'En revision')], db_index=True, default='ACTIVO', max_length=20)),
                ('trimestres_totales', models.PositiveIntegerField(default=6, help_text='Total de trimestres antes de etapa productiva.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VersionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numero de version. Ej: 1, 2.')),
                ('descripcion', models.TextField(blank=True)),
                ('vigente', models.BooleanField(db_index=True, default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='programa.programa')),
            ],
            options={
                'verbose_name': 'Version de programa',
                'verbose_name_plural': 'Versiones de programa',
                'ordering': ['programa', '-numero'],
                'unique_together': {('programa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(help_text='Posicion del modulo dentro de la version.')),
                ('horas_lectivas', models.PositiveIntegerField()),
                ('horas_practicas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='programa.versionprograma')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['version', 'orden'],
                'unique_together': {('version', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='DocenteModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='modulos_asignados', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docentes_asignados', to='programa.modulo')),
            ],
            options={
                'verbose_name': 'Docente por modulo',
                'verbose_name_plural': 'Docentes por modulo',
                'ordering': ['modulo', 'docente'],
                'unique_together': {('docente', 'modulo')},
            },
        ),
    ]
