# Generated by Django 6.0.2 on 2026-06-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_habilitaciondocente_alter_disponibilidad_options_and_more'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='tipo_formacion',
            field=models.CharField(choices=[('POR_OFERTA', 'Por Oferta'), ('CADENA_FORMACION', 'Cadena de Formación'), ('OTRO', 'Otro')], db_index=True, default='POR_OFERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='programa',
            name='trimestres_cadena',
            field=models.PositiveIntegerField(blank=True, help_text='Trimestres en etapa lectiva para cadena de formación. Menor a trimestres_totales.', null=True),
        ),
        migrations.AlterField(
            model_name='docentemodulo',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modulos_asignados', to='docentes.docente'),
        ),
    ]
