# Generated by Django 6.0.2 on 2026-06-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_programa_tipo_formacion_programa_trimestres_cadena_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocenteModulo',
        ),
    ]
