# Generated by Django 6.0.2 on 2026-05-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], db_index=True, max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('MIXTA', 'Mixta')], db_index=True, max_length=10)),
                ('es_recurrente', models.BooleanField(default=True, help_text='True = aplica cada semana. False = solo fecha_especifica.')),
                ('fecha_especifica', models.DateField(blank=True, help_text='Solo si es_recurrente=False.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloques_horario', to='aulas.aula')),
            ],
            options={
                'verbose_name': 'Bloque de horario',
                'verbose_name_plural': 'Bloques de horario',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
