# Generated by Django 6.0.2 on 2026-05-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhorario', '0001_initial'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloques_horario', to='docentes.docente'),
        ),
    ]
