# Generated by Django 6.0.2 on 2026-05-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhorario', '0002_initial'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloques_horario', to='ficha.ficha'),
        ),
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['dia_semana', 'jornada'], name='bhorario_bl_dia_sem_c081c1_idx'),
        ),
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['dia_semana', 'hora_inicio'], name='bhorario_bl_dia_sem_b44253_idx'),
        ),
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['es_recurrente', 'fecha_especifica'], name='bhorario_bl_es_recu_c9114d_idx'),
        ),
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['dia_semana', 'docente', 'hora_inicio', 'hora_fin'], name='idx_bhorario_docente_colision'),
        ),
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['dia_semana', 'aula', 'hora_inicio', 'hora_fin'], name='idx_bhorario_aula_colision'),
        ),
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['dia_semana', 'ficha', 'hora_inicio', 'hora_fin'], name='idx_bhorario_ficha_colision'),
        ),
    ]
