# Generated by Django 6.0.2 on 2026-06-18 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_alter_bloque_estado'),
        ('bhorario', '0004_exclusion_constraints'),
        ('competencia', '0003_delete_docenteasignatura'),
        ('docentes', '0003_migrate_legacy_habilitaciones'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquehorario',
            options={'ordering': ['orden_dia', 'hora_inicio'], 'verbose_name': 'Bloque de horario', 'verbose_name_plural': 'Bloques de horario'},
        ),
        migrations.RemoveIndex(
            model_name='bloquehorario',
            name='bhorario_bl_dia_sem_b44253_idx',
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='competencia',
            field=models.ForeignKey(blank=True, help_text='Desnormalización intencional: permite consultar qué se dicta en este bloque sin hacer join a planificacion. BloqueCompetencia sigue siendo la fuente de verdad para horas ejecutadas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloques_horario', to='competencia.competencia'),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='orden_dia',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Auto-calculado desde dia_semana. 0=Lunes … 5=Sábado.'),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='dia_semana',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['orden_dia', 'hora_inicio'], name='bhorario_bl_orden_d_41df26_idx'),
        ),
    ]
